Commit Sha is now optional
justinsinger/fastlane_plugins pull request #4
Opened 2017-03-24 11:37 UTC by jhanzo

As an enhancement, I suggest some updates :

- [ ] args : 
   - [x] `sha` : Default value is the last commit hash.
   - [ ] `owner` and `repo`: Default values are based on ``git config --get remote.origin.url``
- [ ] Rename `fastlane_plugins` into `fastlane-plugin-github_job_status` and move files for having a clearer file tree.

Please, let me know any suggests, feedbacks or anything else 😉.

2017-03-24 16:06 UTC, justinsinger commented
@jhanzo do you just want to do the default sha in this pull request, or are you also adding the rename?

2017-03-24 18:57 UTC, jhanzo commented
Maybe an another PR would be better ;)

2017-03-24 21:06 UTC, justinsinger requested changes
Just a few minor nits on the README. Also, you have merge conflicts with the version file

2017-03-24 21:06 UTC, justinsinger commented on fastlane-plugin-github_job_status/README.md
> + *`job_name`, `description` and `build_url` are optionals, but all other parameters are required
There must be a space between the asterisk and `job_name` for it to be a bullet point

2017-03-24 21:06 UTC, justinsinger commented on fastlane-plugin-github_job_status/README.md
> + * `sha`, is optional and default value is last commit hash get thanks to lane [last_git_commit](https://docs.fastlane.tools/actions/#last_git_commit)
Could you reword this: "`sha` is optional, and the default value is the last commit hash, thanks to [last_git_commit](https://docs.fastlane.tools/actions/#last_git_commit)"

2017-03-24 21:06 UTC, justinsinger commented on fastlane-plugin-github_job_status/README.md
> + *`job_name`, `description` and `build_url` are optionals, but all other parameters are required
Also, optionals->optional

And take out "but all other parameters are required", since sha is now optional

2017-03-25 10:01 UTC, jhanzo commented
✅ typo README
✅ conflict in version

2017-03-27 19:43 UTC, justinsinger approved these changes

2017-03-27 19:43 UTC, merged

2017-03-27 19:52 UTC, justinsinger commented
@jhanzo 0.2.1 is now released